name: Release

on:
  push:
    tags: 
      - '**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Publish
      run: |
        dotnet publish -o ElgatoLightControl-${{ github.ref_name }} -p:Configuration=Release ElgatoLightControl

    - name: Zip
      run: tar --exclude '*.pdb' -czf elgato-light-control_${{ github.ref_name }}.tar.gz ElgatoLightControl-${{ github.ref_name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ElgatoLightControl_${{ github.ref_name }}-linux
        path: |
          elgato-light-control_${{ github.ref_name }}.tar.gz

  build-windows:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: |
          dotnet publish -o ElgatoLightControl-${{ github.ref_name }} -p:Configuration=Release ElgatoLightControl

      - name: Zip
        run: |
          Get-ChildItem -Path ElgatoLightControl-${{ github.ref_name }} -Recurse -File -Exclude *.pdb | Compress-Archive -DestinationPath elgato-light-control_${{ github.ref_name }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ElgatoLightControl_${{ github.ref_name }}-win
          path: |
            elgato-light-control_${{ github.ref_name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Pull artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: ElgatoLightControl_${{ github.ref_name }}-linux

      - name: Pull artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: ElgatoLightControl_${{ github.ref_name }}-win
        
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          make_latest: true
          target_commitish: main
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            elgato-light-control_${{ github.ref_name }}.tar.gz
            elgato-light-control_${{ github.ref_name }}.zip
